apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: l2-network
  namespace: nad
spec:
  config: |
    {
        "cniVersion": "0.3.1", 1
        "name": "l2-network",
        "type": "ovn-k8s-cni-overlay",
        "topology":"layer2",
        "mtu": 1300,
        "netAttachDefName": nad/l2-network"
        "subnets": "10.170.200.0/24",
    }