apiVersion: v1
kind: Pod
metadata:
  name: nad1
  namespace: nad
  labels:
    app: nad1
  annotations:
    k8s.v1.cni.cncf.io/networks: l2-network
spec:
  runtimeClassName: kata
  containers:
    - name: hello-openshift
      image: quay.io/openshift/origin-hello-openshift
      ports:
        - containerPort: 8888
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

