apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block  # Critical for raw block access
  resources:
    requests:
      storage: 1Gi