# apiVersion: v1
# kind: Pod
# metadata:
#   name: katablock
#   namespace: test
#   labels:
#     app: katablock
# spec:
#   runtimeClassName: kata
#   initContainers:
#   - name: format-disk
#     image: quay.io/centos/centos:stream9 # try this for now
#     restartPolicy: Always  # Native sidecar!
#     securityContext:
#       privileged: true # scope down!!!
#     command: ["/bin/sh", "-c"]
#     args:
#       - |
#         set -e
#         mkdir -p /mnt/storage
#         dnf install -y cryptsetup xfsprogs e2fsprogs # this is a nasty hack
#         if ! blkid /dev/block-device; then
#           echo "creating block device"
#           mkfs.xfs /dev/block-device
#         fi
#         mkdir -p /mnt/storage
#         mount /dev/block-device /mnt/storage
#         echo "Ready"
#         tail -f /dev/null 
#     volumeDevices:
#       - name: csi-block
#         devicePath: /dev/block-device
#   containers:
#     - name: hello-openshift
#       image: quay.io/openshift/origin-hello-openshift
#       ports:
#         - containerPort: 8888
#       securityContext:
#         privileged: false
#         allowPrivilegeEscalation: false
#         runAsNonRoot: true
#         runAsUser: 1001
#         capabilities:
#           drop:
#             - ALL
#         seccompProfile:
#           type: RuntimeDefault
#       volumeDevices:
#         - name: csi-block
#           devicePath: /dev/block-device
#   volumes:

#   - name: csi-block
#     persistentVolumeClaim:
#       claimName: block-pvc
