apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-secondary
  namespace: kata-test-udn
spec:
  topology: Layer3
  layer3:
    role: Secondary
    subnets:
      - cidr: 10.152.0.0/16
        hostSubnet: 24