---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-hsmnetwork
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: br-data
      description: |-
        An OVS bridge for the hsm
      type: ovs-bridge
      state: up
      bridge:
        port:
        - name: bond1
    ovn:
      bridge-mappings:
      - localnet: hsmnetwork
        bridge: br-data
