apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: deny-by-default
  namespace: ripple
  annotations:
    k8s.v1.cni.cncf.io/policy-for: ripple/hsmnetwork
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
