apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: hsmnetwork
  namespace: ripple
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "hsmnetwork",
      "type": "ovn-k8s-cni-overlay",
      "topology":"localnet",
      "subnets": "10.0.1.0/24",
      "physicalNetworkName": "hsmnetwork",
      "netAttachDefName": "ripple/hsmnetwork"
    }
