apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello2
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "hsmnetwork",
          "namespace": "ripple",
          "ips": ["10.0.1.3/24"]
        }
      ]
  name: hello2
  namespace: ripple
spec:
  containers:
  - name: hello-openshift
    image: quay.io/openshift/origin-hello-openshift
    ports:
    - containerPort: 8888
    imagePullPolicy: IfNotPresent
