apiVersion: v1
kind: Service
metadata:
  name: hello1
  namespace: ripple
spec:
  ports:
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: hello1
  sessionAffinity: None
  type: ClusterIP
