apiVersion: v1
kind: Pod
metadata:
  name: standard-secured-pull
  namespace: standard-secured
  labels:
    app: standard-secured-pull

spec:
  initContainers:
    - name: curl
      image: registry.access.redhat.com/ubi9/ubi:9.3 # Lightweight image with curl installed
      command: [ 'sh', '-c', 'curl -s https://registry.access.redhat.com/v2/ > /keys/payload.html' ]
      volumeMounts:
        - name: keys
          mountPath: /keys
  containers:
    - name: coco-demo
      image: registry.access.redhat.com/ubi9/ubi:9.3
      command:
        - sleep
        - "36000"
      securityContext:
        privileged: false
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: keys
          mountPath: /keys
  volumes:
    - name: keys
      emptyDir:
        medium: Memory
