apiVersion: v1
kind: Pod
metadata:
  name: baseline
  labels:
    app: baseline
  annotations:
    io.katacontainers.config.hypervisor.default_memory: "8192"
spec:
  runtimeClassName: kata
  containers:
  - name: hello-openshift
    image: quay.io/openshift/origin-hello-openshift
    ports:
      - containerPort: 8888
    securityContext:
      privileged: true
      runAsUser: 0
    volumeDevices:
      - name: csi-block
        devicePath: /dev/block-device
    command: ["/bin/sh", "-c"]
    args:
      - | 
        set -e
        mkdir -p /mnt/storage
        mount /dev/block-device /mnt/storage
        /hello-openshift
    volumeDevices:
    - name: csi-block
      devicePath: /dev/block-device
  initContainers:
  - name: format-disk
    image: quay.io/centos/centos:stream9 # try this for now
    securityContext:
      privileged: true # scope down!!!
    command: ["/bin/sh", "-c"]
    args:
      - |
        set -e
        mkdir -p /mnt/storage
        dnf install -y cryptsetup xfsprogs e2fsprogs # this is a nasty hack
        if ! blkid /dev/block-device; then
          echo "creating block device"
          mkfs.xfs /dev/block-device
        fi
    volumeDevices:
      - name: csi-block
        devicePath: /dev/block-device
 
  volumes:
  - name: csi-block
    persistentVolumeClaim:
      claimName: block-baseline
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  block-baseline
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block  # Critical for raw block access
  resources:
    requests:
      storage: 1Gi
