apiVersion: v1
kind: Pod
metadata:
  name: iteration-2
  labels:
    app: iteration-2
spec:
  runtimeClassName: kata
  containers:
  - name: hello-openshift
    image: quay.io/openshift/origin-hello-openshift
    ports:
      - containerPort: 8888
    securityContext:
      privileged: true
#      runAsUser: 0
    volumeDevices:
      - name: csi-block
        devicePath: /dev/block-device
    command: ["/bin/sh", "-c"]
    args:
      - | 
        set -e
        /hello-openshift
    volumeDevices:
    - name: csi-block
      devicePath: /dev/block-device
    volumeMounts:
    - name: memory
      mountPath: /mnt/storage
  initContainers:
  - name: format-disk
    image: quay.io/centos/centos:stream9 # try this for now
    securityContext:
      privileged: true # scope down!!!
    restartPolicy: Always  # Native sidecar!
    command: ["/bin/sh", "-c"]
    args:
      - |
        set -e
        dnf install -y cryptsetup xfsprogs e2fsprogs # this is a nasty hack
        if ! blkid /dev/block-device; then
          echo "creating block device"
          mkfs.xfs /dev/block-device
        fi
        mkdir -p /mnt/block
        mount /dev/block-device /mnt/block

        ln -s /mnt/storage/veneer /mnt/block
        tail -f /dev/null 

    volumeDevices:
      - name: csi-block
        devicePath: /dev/block-device
    volumeMounts:
    - name: memory
      mountPath: /mnt/storage
  volumes:
  - name: csi-block
    persistentVolumeClaim:
      claimName: block-iteration-2
  - name: memory
    emptyDir:
      medium: Memory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  block-iteration-2
  accessModes:
    - ReadWriteOnce
  volumeMode: Block  # Critical for raw block access
  resources:
    requests:
      storage: 1Gi