apiVersion: v1
kind: Pod
metadata:
  name: iteration-3
  labels:
    app: iteration-3
spec:
  runtimeClassName: kata
  containers:
  - name: hello-openshift
    image: quay.io/openshift/origin-hello-openshift
    ports:
      - containerPort: 8888
    securityContext:
      privileged: true
#      runAsUser: 0
    command: ["/bin/sh", "-c"]
    args:
      - | 
        set -e
        /hello-openshift
    volumeMounts:
    - name: memory
      mountPath: /mnt/storage
  initContainers:
  - name: format-disk
    image: quay.io/centos/centos:stream9 # try this for now
    securityContext:
      privileged: true # scope down!!!
    restartPolicy: Always  # Native sidecar!
    command: ["/bin/sh", "-c"]
    args:
      - |
        set -e
        dnf install -y cryptsetup xfsprogs e2fsprogs # this is a nasty hack
        DEVICE=/dev/block-device
        MOUNTPOINT=/mnt/storage
        if ! blkid $DEVICE; then
          echo "creating block device"
          mkfs.xfs $DEVICE
        fi
        if ! mount | grep -q "$DEVICE"; then
            sudo mkdir -p "$MOUNTPOINT"
            sudo mount "$DEVICE" "$MOUNTPOINT"
            echo "$DEVICE mounted at $MOUNTPOINT"
        else
            echo "$DEVICE is already mounted."
        fi

    volumeDevices:
      - name: csi-block
        devicePath: /dev/block-device
    volumeMounts:
    - name: memory
      mountPath: /mnt/storage
  volumes:
  - name: csi-block
    persistentVolumeClaim:
      claimName: block-iteration-3
  - name: memory
    emptyDir:
      medium: Memory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-iteration-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block  # Critical for raw block access
  resources:
    requests:
      storage: 1Gi
---