apiVersion: v1
kind: Pod
metadata:
  name: vol-cc-2
  annotations:
    io.katacontainers.config.hypervisor.default_memory: "12228"
    io.katacontainers.config.runtime.create_container_timeout: "900"
spec:
  runtimeClassName: kata-cc
  initContainers:
    - name: vol-sidecar
      image: quay.io/bpradipt/storage-helper:latest
      env:
      - name: NFS_SERVER
        value: "10.8.1.186"
      - name: NFS_SHARE
        value: "/mnt/myshareddir"
      command: ["sh", "-c"]
      args:
      - |
        set -e # Exit immediately if a command exits with a non-zero status.
        echo "cat modules"
        cat /proc/modules
        echo "Mount NFS filesystem..."
        echo "Creating mount point /app-data..."
        mkdir -p /app-data
        mount -t nfs $NFS_SERVER:$NFS_SHARE /app-data
        echo "Mount successful. Sleeping indefinitely..."
        sleep infinity
      securityContext:
        privileged: true
      restartPolicy: Always
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - umount /app-data
  containers:
    - name: app
      image: quay.io/bpradipt/storage-helper:latest
      command: ["sh", "-c"]
      args:
      - sleep infinity
      securityContext:
        privileged: true
      env:
        - name: GET_DATA_PROC_DIR
          value: 'find /proc -maxdepth 1 -type d -regex "/proc/[0-9]*" | head -2 | tail -1'
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - -c
              - ln -s $(eval $GET_DATA_PROC_DIR)/root/app-data /app-data
  shareProcessNamespace: true 
