
---
apiVersion: v1
kind: Pod
metadata:
  name: ssh
spec:
  containers:
  - name: check-kernel
    securityContext: 
      privileged: true # security must be elevated, however, it's within the kata vm
    image: quay.io/rh-ee-chbutler/ssh-client:latest # Any standard UBI container 
    command: ["/bin/sh", "-c"]
    args:
      - |
        tail -f /dev/null